@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "Main",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1969669401 { 
   	label=Array2
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Array21969669401[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Array2</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   M: int[][] [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ average(): double</TD></TR>
<TR><TD ALIGN="LEFT" >+ max(): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ maxStreamApi(): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ printArray()</TD></TR>
<TR><TD ALIGN="LEFT" >+ searchElement(element: int): int[]</TD></TR>
<TR><TD ALIGN="LEFT" >+ sum(): int</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_2390489 { 
   	label=Main
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Main2390489[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Main</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ main(args: String[])</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_63537721 { 
   	label=Array
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Array63537721[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Array</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   V: int[] [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ average(): double</TD></TR>
<TR><TD ALIGN="LEFT" >+ evenNumbers(): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ getFrequency(element: int): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ getIndex(element: int): int[]</TD></TR>
<TR><TD ALIGN="LEFT" >+ isGreaterThan(element: int): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ max(): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ median(): double</TD></TR>
<TR><TD ALIGN="LEFT" >+ min(): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ mode(): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ oddNumbers(): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ printArray()</TD></TR>
<TR><TD ALIGN="LEFT" >+ reverse(array: int[]): int[]</TD></TR>
<TR><TD ALIGN="LEFT" >+ sort(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ sum(): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ sumEvenNumbers(): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ sumOddNumbers(): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ sumRange(start: int, end: int): int</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    

    
}
@enduml